SET SERVEROUTPUT ON

DECLARE
	v_value 			NUMBER := 0;
	v_employee_sequence	VARCHAR2(50) := 'EMPLOYEE_SEQUENCE';
	v_employee_table	VARCHAR2(50) := 'EMPLOYEE_TABLE';
	v_owner				VARCHAR2(50) := 'PIS';
BEGIN
	
	SELECT COUNT(*) 
		INTO v_value
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_employee_sequence;
	
	IF v_value = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_employee_sequence;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_employee_sequence || ' EXCLUIDA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_employee_sequence || ' NAO EXISTE.');
	END IF;
		
	SELECT COUNT(*) 
		INTO v_value
			FROM ALL_TABLES WHERE TABLE_NAME = v_employee_table AND OWNER = v_owner;

	IF v_value = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_employee_table || ' CASCADE CONSTRAINT';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_owner || '.' || v_employee_table || ' EXCLUIDA.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_owner || '.' || v_employee_table || ' NAO EXISTE.');
	END IF;
		
END;
/

CREATE SEQUENCE EMPLOYEE_SEQUENCE 
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'EMPLOYEE_SEQUENCE';

CREATE TABLE EMPLOYEE_TABLE (
Employee_ID NUMBER NOT NULL,
First_Name VARCHAR2(50) NOT NULL,
Last_Name VARCHAR2(50), 
Date_Hire DATE,
CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (Employee_ID));

DESC EMPLOYEE_TABLE;

INSERT INTO EMPLOYEE_TABLE (Employee_ID, First_Name, Last_Name, Date_Hire) VALUES (EMPLOYEE_SEQUENCE.NEXTVAL, 'MARIA', 'DA SILVA', '3-8-1997');
INSERT INTO EMPLOYEE_TABLE (Employee_ID, First_Name, Last_Name, Date_Hire) VALUES (EMPLOYEE_SEQUENCE.NEXTVAL, 'WILLIAN', 'QUEIROZ', '21-7-2000');
INSERT INTO EMPLOYEE_TABLE (Employee_ID, First_Name, Last_Name, Date_Hire) VALUES (EMPLOYEE_SEQUENCE.NEXTVAL, 'ANNA CLAUDIA', NULL, '6-12-2004');
INSERT INTO EMPLOYEE_TABLE (Employee_ID, First_Name, Last_Name, Date_Hire) VALUES (EMPLOYEE_SEQUENCE.NEXTVAL, 'JOÃO', 'ARAUJO', NULL);
			
COMMIT;

SELECT * FROM EMPLOYEE_TABLE;